### ISSUE TITLE
🚕 Move to Human Talks GitHub Organization 

### ISSUE THREAD

**Issue by jeanphibaconnais** [Human-Talks/human-talks-promote-event#6]
This project is for Human Talk. To initiate and test this project this was created on my own repo. But when a first version will be validated, we can move this project https://github.com/humanTalks

**Comment by alexislozano** [comment]
@jeanphibaconnais Ça a l'air bon maintenant, tu devrais pouvoir fermer cette issue :)

**Comment by camilleroux** [comment]
done :)

**Comment by camilleroux** [comment]
done :)
